# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 10
  - name: 研究方向
    # url: /researches/
    url: /#researches
    identifier: research
    weight: 11
  - name: NeuroBaseband
    url: /researches/NeuroBaseband/
    parent: research
    weight: 1
  - name: 边缘 AI 推理引擎
    url: /researches/Edge_AI/
    parent: research
    weight: 2
  # - name: Communication-AI Fusion and Integrated Compute-Communication Architectures for 6G
  #   url: /researches/comm-ai-fusion/
  #   parent: research
  #   weight: 3
  # - name: Project
  #   url: /projects/
  #   weight: 12
  # - name: Teaching
  #   url: /teaching/
  #   weight: 13
  - name: 团队成员
    url: /people/
    weight: 14
  - name: 论文成果
    url: /publication/
    weight: 15
  - name: 实验室活动
    url: /events
    weight: 16
  - name: 加入我们
    url: /opportunities/
    weight: 17
